### ISSUE TITLE
Darf man die App für die eigene Schule verwenden ?

### ISSUE THREAD

**Issue by ghost** [StephanKrauss/schulApp#1]
Hallo, 

Darf ich diese App / WebApp als Grundlage für eine eigene SchulApp verwenden? Wenn ja muss ich Sie irgendwie in den "Quellen" angeben ? 
Ich habe nämlich vor in der Computer AG unserer Schule eine App zu entwickeln, die, ähnlich wie ihre App, den Stundeplan und den Vertretungsplan anzeigt. 

Ihr Jonas Heilemann

**Comment by StephanKrauss** [comment]
Hallo,

entschuldige dass ich jetzt erst antworte.
Du kannst die Skripte / App gern verwenden.
Wenn du Fragen hast, dann helfe ich gern.
In welcher Stadt befindet sich die Schule ? :-)

Gruß Stephan

**Comment by ghost** [comment]
Danke für die Antwort, ich werde einige Skripte de App vermutlich verwenden. Allerdings habe ich bereits einen eigenen "Core" für meine App programmiert, weshalb ich nun nicht alles verwenden kann.
